# golangci-lint v2 configuration
# See https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofumpt       # Stricter gofmt
    - goimports     # Check import order

  settings:
    gofumpt:
      extra-rules: true

linters:
  # Default linters are already enabled: errcheck, govet, ineffassign, staticcheck, unused
  enable:
    - misspell      # Check for misspelled words
    - unconvert     # Remove unnecessary type conversions
    - gocritic      # Opinionated linter with many checks

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    misspell:
      locale: US

issues:
  # Don't limit the number of issues per linter
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gocritic
